apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: shopvac
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-support-weaton-tenant/shopvac/shopvac@sha256:c9937d4185e102814c66e607844586344d01b4eda540e70f57fce0e54da4174c
        name: container-image
        resources: {}
status: {}
