apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: shopvac
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: shopvac
    app.kubernetes.io/part-of: shopvac
  name: shopvac
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: shopvac
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: shopvac
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhn-support-weaton-tenant/shopvac/shopvac@sha256:d9ee75f924e39a0fc11f688a3e405268b4228c36d215ae2e24919dcd20f396e7
        imagePullPolicy: Always
        name: container-image
        resources:
          requests:
            cpu: "1"
            memory: 256Mi
status: {}
